### ISSUE TITLE
Compatibility with RuboCop v1.0

### ISSUE THREAD

**Issue by marcandre** [prontolabs/pronto-rubocop#50]
RuboCop v1.0 is imminent, and looking at this gem there's going to be a few things that might break.
Already the latest release included a change of API for `Team` that [broke things](https://github.com/rubocop-hq/rubocop/issues/8077) (sorry).

I would like to help with the transition for v1. I imagine that compatibility with older versions of RuboCop is important?

**Comment by sunny** [comment]
That would be awesome \o/

I might also be able to help since I think I'm the one that tinkered with the RuboCop API the most recently when adding the autocorrect suggestions.

I am not part of the maintainers so I don't know how compatibility with older RuboCop versions is important. Personnally I'd be okay with having the next version of pronto-rubocop only compatible with RuboCop > 1.0.
